### PR TITLE
Setup dev host

### PR DESCRIPTION
**Pull request by slequeux**

### CODE REVIEW

**Comment by esciara** [comment]
The first commit (da4a62c) should not be there. I changed the directory's name, that is probably why you get this problem. I renamed it from `{{cookiecutter.project_slug}}` to `{{cookiecutter.project_package_name}}`.

Can you make the correction please?

**Comment by esciara** [comment]
@slequeux @antoinemichaud , I fixed issues, cleaned it up and all is working now. Please could you check and give me some feedback?

**Comment by slequeux** [comment]
> @slequeux @antoinemichaud , I fixed issues, cleaned it up and all is working now. Please could you check and give me some feedback?

Proposed refactoring does not work. Simply running `tests/run_tests.sh` do not work anymore.
You removed some fixes we put regarding to a bug (not sourcing .bashrc but directly putting theses lines) we documented in a comment.

Could you also squash some commits to make them readable ?

**Comment by esciara** [comment]
> Proposed refactoring does not work. Simply running `tests/run_tests.sh` do not work anymore.
> You removed some fixes we put regarding to a bug (not sourcing .bashrc but directly putting theses lines) we documented in a comment.

Errr... not according to the pipeline (which I just set up)... And I ran it again on my mac, and it works fine.

> Could you also squash some commits to make them readable ?

Done. Let me know whether it all works for you.

**Comment by esciara** [comment]
reviewed together with @slequeux and @antoinemichaud .

**Pull request merged**
